[package]
name = "core_graphics_min"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A reimplementation of a few CoreGraphics types in Rust."
readme = "README.md"
repository = "https://github.com/rizerco/core_graphics_min"

[dependencies]
